In [4]:
import numpy as np
array_a = np.arange(1, 11)
print(array_a)

array_b = np.arange(0.5, 5.25, 0.25)
print(array_b)

[ 1  2  3  4  5  6  7  8  9 10]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


In [6]:
zeros_a = np.zeros(10)
print(zeros_a)

zeros_b = np.zeros((4, 3))
print(zeros_b)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
linspace_a = np.linspace(2, 12, 5)
print(linspace_a)

linspace_b = np.linspace(3, 9, 4)
print(linspace_b)


[ 2.   4.5  7.   9.5 12. ]
[3. 5. 7. 9.]


In [10]:
random_a = np.random.rand(2, 4)
print(random_a)

random_b = np.random.randint(10, 20, (3, 3))
print(random_b)

reshaped_a = random_a.reshape(8, 1)
print(reshaped_a)


[[0.57154041 0.39517928 0.77151721 0.81160032]
 [0.91485406 0.26586794 0.14835901 0.99243074]]
[[14 15 13]
 [19 13 16]
 [10 19 17]]
[[0.57154041]
 [0.39517928]
 [0.77151721]
 [0.81160032]
 [0.91485406]
 [0.26586794]
 [0.14835901]
 [0.99243074]]


In [ ]:
5. If we use a fixed seed, the sequence of random numbers will be the same each time, allowing reproducibility.
Advantage of using seed: It ensures consistency in results, useful for testing and debugging.

In [12]:
user_numbers = []
for _ in range(5):
    num = float(input("Enter a number: "))
    user_numbers.append(num)


Enter a number:  1
Enter a number:  2
Enter a number:  3
Enter a number:  4
Enter a number:  5


In [ ]:
array_user = np.array(user_numbers)
